import type { DecisionDoc } from "./decision-model";

export const sampleDecision: DecisionDoc = {
  id: "sample",
  title: "Should I leave my current school?",
  question: "Should I leave my current school?",
  depth: "high",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  context: [
    {
      label: "Situation",
      value: "Two years in, academically fine, socially settled, quietly bored.",
    },
    { label: "Wants", value: "Stronger science teaching without starting over from zero." },
    { label: "Constraints", value: "Family stays in the same city; tuition can't go up much." },
  ],
  criteria: ["Time cost", "Risk", "Flexibility kept", "Fit with what you want"],
  assumptions: [
    { id: "speed", label: "Speed matters most", hint: "You'd rather not lose a year." },
    { id: "money", label: "Budget is tighter than expected" },
    { id: "near-home", label: "Staying near home becomes essential" },
  ],
  insights: [
    { text: "The real tradeoff here isn't money. It's a year of momentum.", emphasis: true },
    { text: "Two of your three paths are reversible. That matters more than it sounds." },
    {
      text: "You keep describing boredom, not failure — that points to changing depth, not changing buildings.",
    },
  ],
  recommendation: {
    pathId: "stay",
    lean: "I'd lean toward staying, but changing what staying looks like.",
    why: "It gets you most of what you're missing — harder science, new people — without spending a year on the transition.",
    downside:
      "If the school genuinely can't offer more depth, you'll have lost a term finding that out.",
    uncertain: "How much of the boredom is the school and how much is the stage you're at.",
    couldChange:
      "If you talk to the department and they can't stretch you, transferring becomes the stronger path.",
  },
  root: {
    id: "root",
    kind: "root",
    label: "Should I leave my current school?",
    summary: "Three realistic directions, each with a different cost.",
    children: [
      {
        id: "stay",
        kind: "path",
        label: "Stay, but change how you're there",
        summary: "Same school, different intensity — harder courses, outside programmes.",
        tradeoff: "Lowest cost, but relies on the school actually having more to give.",
        risk: "low",
        scores: { "Time cost": 15, Risk: 25, "Flexibility kept": 85, "Fit with what you want": 62 },
        strongerWhen: ["speed", "money", "near-home"],
        timeline: [
          { label: "Talk to the science department", when: "This month" },
          { label: "Pick two stretch commitments", when: "Next term" },
          { label: "Review honestly", when: "In six months" },
        ],
        why: "You're bored, not stuck. Boredom is often cheaper to fix than it feels.",
        upside:
          "Nothing is lost. Your friendships, your track record and your timeline stay intact.",
        watch: "Doing this half-heartedly gives you the same year back, unchanged.",
        next: "One conversation with the department tells you most of what you need.",
        pros: ["Keeps every other option open", "No year lost", "Costs nothing"],
        cons: ["Depends on the school flexing", "Easy to drift back into the same routine"],
        children: [
          {
            id: "stay-depth",
            kind: "consequence",
            label: "The school can stretch you",
            summary: "Advanced sets, a research project, an outside olympiad track.",
            risk: "low",
            tradeoff: "More work on top of an already full year.",
            timeline: [{ label: "First stretch project", when: "Term 2" }],
            children: [
              {
                id: "stay-depth-out",
                kind: "outcome",
                label: "Same school, sharper year",
                summary: "You get the depth without the disruption.",
                risk: "low",
              },
            ],
          },
          {
            id: "stay-flat",
            kind: "consequence",
            label: "Nothing really changes",
            summary: "The offer exists on paper but not in practice.",
            risk: "medium",
            tradeoff: "You've spent a term confirming a suspicion.",
            children: [
              {
                id: "stay-flat-decision",
                kind: "decision",
                label: "Revisit transferring — with evidence",
                summary: "You'd apply knowing exactly what you're missing.",
                risk: "low",
              },
            ],
          },
        ],
      },
      {
        id: "transfer",
        kind: "path",
        label: "Transfer to another school",
        summary: "A clean change of environment, mid-way through.",
        tradeoff: "You trade two years of standing for a stronger programme.",
        risk: "medium",
        scores: { "Time cost": 55, Risk: 65, "Flexibility kept": 45, "Fit with what you want": 80 },
        strongerWhen: ["speed"],
        weakerWhen: ["money", "near-home"],
        why: "If the ceiling is the school itself, no amount of effort inside it moves the ceiling.",
        upside: "A programme built for the thing you actually want to do.",
        watch: "Transfer years are socially expensive in a way people underestimate.",
        next: "Visit two schools before deciding anything.",
        pros: ["Real change in teaching quality", "New peer group", "Fresh start"],
        cons: ["Friendships thin out", "Admissions timing is rigid", "Possible cost increase"],
        timeline: [
          { label: "Shortlist and visit", when: "Next 6 weeks" },
          { label: "Applications", when: "Autumn" },
          { label: "Decision and handover", when: "Spring" },
          { label: "Start", when: "September" },
        ],
        children: [
          {
            id: "transfer-good",
            kind: "consequence",
            label: "It fits",
            summary: "Better teaching, and you find your footing by the second term.",
            risk: "low",
            children: [
              {
                id: "transfer-good-out",
                kind: "outcome",
                label: "Stronger final two years",
                summary: "You end up where you wanted, one hard term later.",
                risk: "low",
              },
            ],
          },
          {
            id: "transfer-hard",
            kind: "consequence",
            label: "The settling-in is harder than expected",
            summary: "Academically better, socially thinner for a while.",
            risk: "high",
            tradeoff: "Short-term wellbeing against long-term fit.",
            children: [
              {
                id: "transfer-hard-decision",
                kind: "decision",
                label: "Stay the course or step back",
                summary: "Most people who push through report it evens out by month four.",
                risk: "medium",
              },
            ],
          },
        ],
      },
      {
        id: "gap",
        kind: "path",
        label: "Take a gap year first",
        summary: "Step out, build something, decide from a clearer place.",
        tradeoff: "Buys clarity and flexibility, spends a year of time.",
        risk: "medium",
        scores: { "Time cost": 90, Risk: 50, "Flexibility kept": 70, "Fit with what you want": 55 },
        strongerWhen: ["near-home"],
        weakerWhen: ["speed"],
        why: "If you genuinely don't know what you want yet, a year of real-world contact is not wasted.",
        upside: "You come back to the decision with information you can't get from inside school.",
        watch: "Unstructured gap years drift. This one needs a shape before it starts.",
        next: "Write down what would make the year a success before committing.",
        pros: ["Time to test what you actually like", "Keeps both school options alive"],
        cons: ["A year behind your cohort", "Needs real structure to be worth it"],
        timeline: [
          { label: "Define what the year is for", when: "Before committing" },
          { label: "Line up work or a programme", when: "3 months out" },
          { label: "Mid-year review", when: "Month 6" },
          { label: "Re-decide with better information", when: "Month 10" },
        ],
        children: [
          {
            id: "gap-clear",
            kind: "consequence",
            label: "You come back with a direction",
            summary: "The school question answers itself once you know what you're aiming at.",
            risk: "low",
          },
          {
            id: "gap-drift",
            kind: "consequence",
            label: "The year drifts",
            summary: "No structure, no new information, twelve months gone.",
            risk: "high",
            tradeoff:
              "The worst version of this path is worse than the worst version of the others.",
          },
        ],
      },
    ],
  },
};
