/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProRouteImport } from './routes/pro'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DecisionsIndexRouteImport } from './routes/decisions.index'
import { Route as DecisionsIdRouteImport } from './routes/decisions.$id'
import { Route as ApiWebhooksPaddleRouteImport } from './routes/api/webhooks/paddle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsIndexRoute = DecisionsIndexRouteImport.update({
  id: '/decisions/',
  path: '/decisions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsIdRoute = DecisionsIdRouteImport.update({
  id: '/decisions/$id',
  path: '/decisions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaddleRoute = ApiWebhooksPaddleRouteImport.update({
  id: '/api/webhooks/paddle',
  path: '/api/webhooks/paddle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/decide': typeof DecideRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/terms': typeof TermsRoute
  '/decisions/$id': typeof DecisionsIdRoute
  '/decisions/': typeof DecisionsIndexRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/decide': typeof DecideRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/terms': typeof TermsRoute
  '/decisions/$id': typeof DecisionsIdRoute
  '/decisions': typeof DecisionsIndexRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/decide': typeof DecideRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/terms': typeof TermsRoute
  '/decisions/$id': typeof DecisionsIdRoute
  '/decisions/': typeof DecisionsIndexRoute
  '/api/webhooks/paddle': typeof ApiWebhooksPaddleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptable-use'
    | '/billing'
    | '/contact'
    | '/cookies'
    | '/decide'
    | '/disclaimer'
    | '/privacy'
    | '/pro'
    | '/terms'
    | '/decisions/$id'
    | '/decisions/'
    | '/api/webhooks/paddle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptable-use'
    | '/billing'
    | '/contact'
    | '/cookies'
    | '/decide'
    | '/disclaimer'
    | '/privacy'
    | '/pro'
    | '/terms'
    | '/decisions/$id'
    | '/decisions'
    | '/api/webhooks/paddle'
  id:
    | '__root__'
    | '/'
    | '/acceptable-use'
    | '/billing'
    | '/contact'
    | '/cookies'
    | '/decide'
    | '/disclaimer'
    | '/privacy'
    | '/pro'
    | '/terms'
    | '/decisions/$id'
    | '/decisions/'
    | '/api/webhooks/paddle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  BillingRoute: typeof BillingRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DecideRoute: typeof DecideRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  ProRoute: typeof ProRoute
  TermsRoute: typeof TermsRoute
  DecisionsIdRoute: typeof DecisionsIdRoute
  DecisionsIndexRoute: typeof DecisionsIndexRoute
  ApiWebhooksPaddleRoute: typeof ApiWebhooksPaddleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/': {
      id: '/decisions/'
      path: '/decisions'
      fullPath: '/decisions/'
      preLoaderRoute: typeof DecisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$id': {
      id: '/decisions/$id'
      path: '/decisions/$id'
      fullPath: '/decisions/$id'
      preLoaderRoute: typeof DecisionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paddle': {
      id: '/api/webhooks/paddle'
      path: '/api/webhooks/paddle'
      fullPath: '/api/webhooks/paddle'
      preLoaderRoute: typeof ApiWebhooksPaddleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  BillingRoute: BillingRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DecideRoute: DecideRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  ProRoute: ProRoute,
  TermsRoute: TermsRoute,
  DecisionsIdRoute: DecisionsIdRoute,
  DecisionsIndexRoute: DecisionsIndexRoute,
  ApiWebhooksPaddleRoute: ApiWebhooksPaddleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
